name: capston
description: Campus IAQ Flutter Web
version: 0.0.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^2.4.0
  google_fonts: ^6.2.1
  fl_chart: ^1.1.1
  args: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/data.json
    - assets/data/mul.json